import { defineConfig } from "@unocss/vite";
import presetWind from "@unocss/preset-wind";
import presetAttributify from "@unocss/preset-attributify";
import presetWebFonts from "@unocss/preset-web-fonts";
import presetIcons from "@unocss/preset-icons";
import transformerVariantGroup from "@unocss/transformer-variant-group";
import extractorSvelte from "@unocss/extractor-svelte";

const colorVar = (name: string) => `rgba(var(--color-${name}), <alpha-value>)`;
const fixedColorVar = (name: string) => `var(--color-${name})`;

export default defineConfig({
  presets: [
    presetAttributify(),
    presetWind(),
    presetIcons(),
    presetWebFonts({
      fonts: {
        sans: [
          {
            name: "Noto Sans JP",
            weights: ["400", "500", "700"],
          },
        ],
        logo: [
          {
            name: "Space Mono",
            weights: ["400"],
          },
        ],
      },
    }),
  ],
  extractors: [extractorSvelte()],
  safelist: [
    "i-iconoir-cancel",
    "i-iconoir-plus",
    "i-iconoir-youtube",
    "i-material-symbols:check-box-outline-blank",
    "i-material-symbols:close",
    "i-material-symbols:filter-none",
    "i-material-symbols:remove",
    "i-material-symbols-power-rounded",
    "i-material-symbols-folder-open-rounded",
    "i-material-symbols-drive-file-rename-outline",
    "i-material-symbols-qr-code",
    "i-material-symbols-favorite-rounded",
    "i-material-symbols-favorite-outline-rounded",
    "i-material-symbols-menu-rounded",
    "i-material-symbols-arrow-drop-down",
    "i-material-symbols-history-rounded",
    "i-material-symbols-hourglass-outline-rounded",
    "i-material-symbols-play-circle-outline-rounded",
    "i-material-symbols-pause-circle-outline-rounded",
    "i-material-symbols-check-circle-outline-rounded",
    "i-material-symbols-home-rounded",
    "i-material-symbols-add-circle-outline-rounded",
    "i-material-symbols-grid-view-rounded",
    "i-material-symbols-list-rounded",
    "i-material-symbols-help-outline-rounded",
    "i-material-symbols-open-in-new",
    "i-material-symbols-apps",
    "i-material-symbols-arrow-forward-ios-rounded",
    "i-material-symbols-cancel-outline-rounded",
    "i-material-symbols-check",
    "i-material-symbols-check-box-outline-blank",
    "i-material-symbols-check-box-rounded",
    "i-material-symbols-check-circle-rounded",
    "i-material-symbols-checklist",
    "i-material-symbols-check-small-rounded",
    "i-material-symbols-chevron-left",
    "i-material-symbols-chevron-right",
    "i-material-symbols-circle-outline",
    "i-material-symbols-close-rounded",
    "i-material-symbols-computer-outline-rounded",
    "i-material-symbols-content-copy-outline-rounded",
    "i-material-symbols-dark-mode-outline",
    "i-material-symbols-delete",
    "i-material-symbols-display-settings-outline",
    "i-material-symbols-download-rounded",
    "i-material-symbols-done-all-rounded",
    "i-material-symbols-flip-to-back-outline-rounded",
    "i-material-symbols-folder-outline-rounded",
    "i-material-symbols-image",
    "i-material-symbols-image-not-supported",
    "i-material-symbols-image-not-supported-outline",
    "i-material-symbols-image-outline",
    "i-material-symbols-keyboard-outline",
    "i-material-symbols-label-outline-rounded",
    "i-material-symbols-left-panel-close-outline",
    "i-material-symbols-library-add-check-outline-rounded",
    "i-material-symbols-light-mode-outline",
    "i-material-symbols-open-in-new-rounded",
    "i-material-symbols-palette-outline",
    "i-material-symbols-pause-circle-outline",
    "i-material-symbols-play-arrow-rounded",
    "i-material-symbols-play-circle-rounded",
    "i-material-symbols-power-settings-new-rounded",
    "i-material-symbols-refresh-rounded",
    "i-material-symbols-remove-done-rounded",
    "i-material-symbols-search",
    "i-material-symbols-settings-outline",
    "i-material-symbols-sort-rounded",
    "i-material-symbols-sports-esports-outline",
    "i-material-symbols-system-update-alt-rounded",
    "i-material-symbols-upload",
    "i-material-symbols-view-list-outline-rounded",
    "i-material-symbols-view-module-outline-rounded",
    "i-material-symbols-warning-outline-rounded",
  ],
  transformers: [transformerVariantGroup()],
  shortcuts: {
    glass: "bg-bg-primary/60 backdrop-blur-md border-white/10",
    "glass-hover": "hover:bg-bg-primary/70 transition-colors duration-200",
    "focus-ring": "focus:outline-none focus-visible:outline-none",
  },
  theme: {
    colors: {
      accent: {
        accent: colorVar("accent-accent"),
        primary: colorVar("accent-primary"),
        primaryHover: colorVar("accent-primary-hover"),
        success: colorVar("accent-success"),
        edit: colorVar("accent-edit"),
        warning: colorVar("accent-warning"),
        error: colorVar("accent-error"),
      },
      bg: {
        primary: colorVar("bg-primary"),
        secondary: colorVar("bg-secondary"),
        tertiary: colorVar("bg-tertiary"),
        disabled: colorVar("bg-disabled"),
        button: colorVar("bg-button"),
        buttonHover: colorVar("bg-button-hover"),
        backdrop: colorVar("bg-backdrop"),
        successDisabled: fixedColorVar("bg-success-disabled"),
        successHover: colorVar("bg-success-hover"),
        warning: colorVar("bg-warning"),
        t_primary: colorVar("bg-t-primary"),
        t_secondary: colorVar("bg-t-secondary"),
        t_tertiary: colorVar("bg-t-tertiary"),
      },
      ui: { tertiary: colorVar("ui-tertiary") },
      border: {
        primary: fixedColorVar("border-primary"),
        button: colorVar("border-button"),
        buttonHover: colorVar("border-button-hover"),
        warning: colorVar("border-warning"),
        successDisabled: fixedColorVar("border-success-disabled"),
      },
      text: {
        primary: colorVar("text-primary"),
        secondary: colorVar("text-secondary"),
        tertiary: colorVar("text-tertiary"),
        link: colorVar("text-link"),
        white: colorVar("text-white"),
        disabled: colorVar("text-disabled"),
        successDisabled: fixedColorVar("text-success-disabled"),
        b_primary: colorVar("text-b-primary"),
        b_secondary: colorVar("text-b-secondary"),
        b_tertiary: colorVar("text-b-tertiary"),
      },
    },
    fontSize: {
      body: ["1rem", "160%"],
      body2: [".875rem", "160%"],
      body3: [".8rem", "160%"],
      h1: ["1.75rem", "145%"],
      h2: ["1.5rem", "145%"],
      h3: ["1.25rem", "145%"],
      h4: ["1.125rem", "145%"],
      caption: [".75rem", "142%"],
      input: [".875rem", "100%"],
    },
  },
});
