<script lang="ts">
  import type { ComponentType } from "svelte";
  import Router from "svelte-spa-router";
  import { routes } from "@/router/route";
  import { initialize, routeLoaded, syncSelectedToLocation } from "@/store/tabs";
  import { onMount } from "svelte";
  import { setupHistoryTracker } from "@/lib/historyTrack";
  import { backgroundState } from "@/store/background";
  import { location, replace } from "svelte-spa-router";
  import { fade } from "svelte/transition";
  import { isWorkDetailRoute } from "@/lib/routeHelper";
  import { setupGlobalErrorLogging } from "@/lib/errors";

  $: isWorkDetail = isWorkDetailRoute($location);

  import { getCurrentWindow } from "@tauri-apps/api/window";

  import InitializationOverlay from "@/components/UI/InitializationOverlay.svelte";
  import { theme } from "@/store/theme";

  const windowLabel = getCurrentWindow().label;
  const isPublicDemoBuild = __PUBLIC_DEMO_BUILD__;
  type ComponentModule = { default: ComponentType };
  let didInitializeMainApp = false;
  let isMounted = false;
  let overlayComponentPromise: Promise<ComponentModule> | null = null;
  let screenshotWindowComponentPromise: Promise<ComponentModule> | null = null;
  let trayMenuComponentPromise: Promise<ComponentModule> | null = null;
  let landingComponentPromise: Promise<ComponentModule> | null = null;
  let titleBarComponentPromise: Promise<ComponentModule> | null = null;
  let layoutComponentPromise: Promise<ComponentModule> | null = null;
  let importDropFilesComponentPromise: Promise<ComponentModule> | null = null;
  let didStartDetailRegistration = false;
  let setDetailPromise: Promise<void> = Promise.resolve();

  $: isLandingRoute =
    isPublicDemoBuild && ($location === "/" || $location === "/landing");
  $: if (windowLabel === "overlay" && !overlayComponentPromise) {
    overlayComponentPromise = import("@/views/Overlay.svelte");
  }
  $: if (
    windowLabel === "screenshot_window" &&
    !screenshotWindowComponentPromise
  ) {
    screenshotWindowComponentPromise = import("@/views/ScreenshotWindow.svelte");
  }
  $: if (windowLabel === "tray_menu" && !trayMenuComponentPromise) {
    trayMenuComponentPromise = import("@/views/TrayMenu.svelte");
  }
  $: if (isLandingRoute && !landingComponentPromise) {
    landingComponentPromise = import("@/views/Landing.svelte");
  }
  $: if (
    windowLabel === "main" &&
    !isLandingRoute &&
    !titleBarComponentPromise
  ) {
    titleBarComponentPromise = import("@/components/TitleBar.svelte");
  }
  $: if (
    windowLabel === "main" &&
    !isLandingRoute &&
    !layoutComponentPromise
  ) {
    layoutComponentPromise = import("@/layouts/Layout.svelte");
  }
  $: if (
    windowLabel === "main" &&
    !isLandingRoute &&
    !importDropFilesComponentPromise
  ) {
    importDropFilesComponentPromise = import(
      "@/components/Home/ImportDropFiles.svelte"
    );
  }
  $: if (isLandingRoute) {
    setDetailPromise = Promise.resolve();
  } else if (!didStartDetailRegistration) {
    didStartDetailRegistration = true;
    setDetailPromise = import("@/lib/registerCollectionElementDetails").then(
      ({ registerCollectionElementDetails }) =>
        registerCollectionElementDetails(),
    );
  }
  $: if ($location === "/settings/display") {
    replace("/settings/shortcut");
  }
  $: if (!isLandingRoute) {
    syncSelectedToLocation($location);
  }

  const handleMainScroll = (e: Event) => {
    const target = e.currentTarget as HTMLElement;
    if (target.scrollTop !== 0) {
      target.scrollTop = 0;
    }
  };

  const initializeMainApp = () => {
    if (didInitializeMainApp) {
      return;
    }
    didInitializeMainApp = true;
    initialize();
    void import("@/lib/scrapeAllGame").then(({ initializeAllGameCache }) =>
      initializeAllGameCache(),
    );
    void import("@/store/works").then(({ works }) =>
      works.ensureRegisteredStories(),
    );
  };

  const initializeAppUpdate = () => {
    void import("@/store/update").then(({ appUpdate }) =>
      appUpdate.initialize(),
    );
  };

  onMount(() => {
    void theme.initialize();
    isMounted = true;
    const cleanupGlobalErrorLogging = setupGlobalErrorLogging();
    // Remove stale demo memo samples generated by older demo builds.
    const demoIds = [39837, 27059, 38696, 38631, 26245, 28941, 30122, 25861, 20988, 31106, 31597, 38794];
    demoIds.forEach((id) => {
      const key = `smde_memo-${id}`;
      const val = localStorage.getItem(key);
      if (val && (val.includes("自動生成サンプルメモ") || val.includes("攻略進捗とメモ"))) {
        localStorage.removeItem(key);
      }
    });

    if (!isLandingRoute) {
      initializeMainApp();

      if (windowLabel === "main") {
        initializeAppUpdate();
      }
    }


    let cleanupTooltips = () => {};
    let didUnmount = false;
    void import("@/lib/tooltip").then(({ setupGlobalTooltips }) => {
      if (didUnmount) {
        return;
      }
      cleanupTooltips = setupGlobalTooltips();
    });
    const cleanupHistory = setupHistoryTracker();

    // Prevent the WebView from scrolling after focus moves.
    const handleFocusIn = () => {
      setTimeout(() => {
        if (window.scrollY !== 0) {
          window.scrollTo(0, 0);
        }
        const mainElement = document.querySelector("main");
        if (mainElement && mainElement.scrollTop !== 0) {
          mainElement.scrollTop = 0;
        }
      }, 0);
    };
    document.addEventListener("focusin", handleFocusIn);

    const preventScroll = () => {
      if (window.scrollY !== 0) {
        window.scrollTo(0, 0);
      }
    };
    window.addEventListener("scroll", preventScroll, { passive: true });

    // Disable reload shortcuts inside the app shell.
    const handleKeydown = (e: KeyboardEvent) => {
      if (
        e.key === "F5" ||
        (e.ctrlKey && e.key === "r") ||
        (e.metaKey && e.key === "r")
      ) {
        e.preventDefault();
      }
    };
    window.addEventListener("keydown", handleKeydown);

    return () => {
      didUnmount = true;
      window.removeEventListener("keydown", handleKeydown);
      document.removeEventListener("focusin", handleFocusIn);
      window.removeEventListener("scroll", preventScroll);
      cleanupGlobalErrorLogging();
      cleanupTooltips();
      cleanupHistory();
    };
  });

  $: if (isMounted && !isLandingRoute) {
    initializeMainApp();
    if (windowLabel === "main") {
      initializeAppUpdate();
    }
  }
</script>

{#if windowLabel === "overlay" && overlayComponentPromise}
  {#await overlayComponentPromise then module}
    <svelte:component this={module.default} />
  {/await}
{:else if windowLabel === "screenshot_window" && screenshotWindowComponentPromise}
  {#await screenshotWindowComponentPromise then module}
    <svelte:component this={module.default} />
  {/await}
{:else if windowLabel === "tray_menu" && trayMenuComponentPromise}
  {#await trayMenuComponentPromise then module}
    <svelte:component this={module.default} />
  {/await}
{:else if isLandingRoute && landingComponentPromise}
  {#await landingComponentPromise then module}
    <svelte:component this={module.default} />
  {/await}
{:else}
  <main
    class="relative h-full w-full font-sans overflow-hidden flex flex-col transition-colors duration-300"
    class:bg-bg-primary={!isWorkDetail}
    class:bg-transparent={isWorkDetail}
    on:scroll={handleMainScroll}
  >
    {#if titleBarComponentPromise}
      {#await titleBarComponentPromise then module}
        <svelte:component this={module.default} heightClass="h-10" />
      {/await}
    {/if}
    {#if $backgroundState.imageUrl}
      {#key $backgroundState.imageUrl}
        <div
          transition:fade={{ duration: 300 }}
          class="absolute inset-0 bg-cover bg-center z-0 transition-all duration-500 ease-out transform"
          class:opacity-85={isWorkDetail}
          class:scale-100={isWorkDetail}
          class:blur-2xl={!isWorkDetail}
          class:opacity-50={!isWorkDetail}
          style="background-image: url('{$backgroundState.imageUrl}'); {isWorkDetail ? 'filter: blur(64px) brightness(1.0);' : ''}"
        />
      {/key}
    {/if}
    <div class="relative flex-1 w-full z-10 min-h-0">
      {#await setDetailPromise then _}
        {#if layoutComponentPromise}
          {#await layoutComponentPromise then module}
            <svelte:component this={module.default}>
              {#key $location}
                <div
                  class="absolute inset-0"
                  in:fade={{ duration: 200, delay: 200 }}
                  out:fade={{ duration: 200 }}
                >
                  <Router {routes} on:routeLoaded={routeLoaded} />
                </div>
              {/key}
            </svelte:component>
          {/await}
        {/if}
      {/await}
      {#if importDropFilesComponentPromise}
        {#await importDropFilesComponentPromise then module}
          <svelte:component this={module.default} />
        {/await}
      {/if}
      <InitializationOverlay />
    </div>
  </main>
{/if}
