name: Create Release and Upload Artifacts

on:
  push:
    branches:
      - 'v?[0-9]+(\.[0-9]+)+-artifacts'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the tag name
      id: get_tag
      run: echo "tag=$(echo $GITHUB_REF | cut -d / -f 3 | cut -d - -f 1) >> $GITHUB_OUTPUT"

    - name: Get the version
      id: get_version
      run: echo "version=$(${{ steps.get_tag.outputs.tag }} | sed 's/^v//') >> $GITHUB_OUTPUT"
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.get_tag.outputs.tag }}
        prerelease: true
        title: "Release ${{ steps.get_tag.outputs.tag }}"
        files: |
          ./src-tauri/target/release/bundle/msi/*
